version: '3'
services:
  service:
    image: chuangoing-start-1/webapiservice
    build:
      context: .
      dockerfile: ChuanGoing.Web.API/Dockerfile
    ports:
      - 9020:9020
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:9020
    container_name: webapiservice