apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s-deployment.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: service
  name: service
spec:
  ports:
  - name: "9020"
    port: 9020
    targetPort: 9020
  selector:
    io.kompose.service: service
status:
  loadBalancer: {}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s-deployment.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: service
  name: service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: service
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://*:9020
        image: chuangoingdocker/chuangoing-start-1:latest
        name: webapiservice
        ports:
        - containerPort: 9020
        resources: {}
      restartPolicy: Always
status: {}
